# Generated by Django 5.2.4 on 2025-12-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VyPpro.servicio')),
            ],
        ),
    ]
