# Generated by Django 5.2.4 on 2025-12-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='empresa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
