# Generated by Django 5.2.4 on 2025-12-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0002_alter_formulario_empresa_alter_formulario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='apellido',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
