# Generated by Django 5.2.4 on 2025-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0003_formulario_apellido_formulario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='servicio'),
        ),
    ]
