# Generated by Django 5.2.4 on 2025-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0004_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
