# Generated by Django 5.2.4 on 2025-12-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0005_alter_formulario_id_alter_formulario_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VyPpro.servicio')),
            ],
            options={
                'verbose_name': 'Fotos',
                'verbose_name_plural': 'fotos de trabajos',
            },
        ),
    ]
