# Generated by Django 5.2.4 on 2025-12-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0007_remove_galeria_servicio_galeria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='¿Revisado?'),
        ),
    ]
