# Generated by Django 5.2.4 on 2025-12-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0008_formulario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar en la pagina web?'),
        ),
    ]
