# Generated by Django 5.2.4 on 2025-12-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0009_servicio_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
