# Generated by Django 5.2.4 on 2025-12-30 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0010_alter_formulario_apellido_alter_formulario_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulario de Contactos', 'verbose_name_plural': 'Bandeja de Entrada'},
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de envío'),
            preserve_default=False,
        ),
    ]
