# Generated by Django 5.2.4 on 2025-12-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0011_alter_formulario_options_formulario_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Servicios'},
        ),
    ]
