# Generated by Django 5.2.4 on 2025-12-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0013_alter_formulario_options_alter_galeria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
