# Generated by Django 5.2.4 on 2026-01-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0015_galeria_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VyPro.servicio'),
        ),
    ]
