# Generated by Django 5.2.4 on 2026-01-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0016_alter_galeria_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria de trabajos'},
        ),
        migrations.AlterField(
            model_name='formulario',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VyPpro.servicio', verbose_name='Tipo de servicios'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VyPpro.servicio', verbose_name='Tipo de servicio'),
        ),
    ]
