# Generated by Django 5.2.4 on 2026-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPpro', '0017_alter_galeria_options_alter_formulario_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='¿Formulario revisado?'),
        ),
    ]
