# Generated by Django 5.2.4 on 2025-12-24 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0006_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='servicio',
        ),
        migrations.AddField(
            model_name='galeria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
