# Generated by Django 5.2.4 on 2025-12-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0012_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Formulario de Contactos', 'verbose_name_plural': 'Bandeja de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria de trabajos'},
        ),
    ]
