# Generated by Django 5.2.4 on 2026-01-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VyPro', '0014_alter_formulario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='VyPro.servicio'),
        ),
    ]
